version: "3.9"
services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./data/db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
volumes:
    mongodata:
    node_modules:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./node_modules

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: ${MONGO_SUBNET}
                    gateway: ${MONGO_GATEWAY}